# Generated by Django 3.2.7 on 2021-11-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_app', '0003_alter_event_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='start_time_string',
            field=models.TextField(null=True),
        ),
    ]
