# Generated by Django 3.2.7 on 2021-11-18 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_app', '0004_event_start_time_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_time_string',
            field=models.TextField(null=True),
        ),
    ]
