# Generated by Django 3.2.7 on 2021-11-17 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_delete_pdf'),
        ('s3p3', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.class'),
        ),
    ]
